Hadolint fixes (#235)
* chore: add .hadolint.yaml config to ignore version pinning and latest tag rules

* fix(images): use JSON notation for CMD to fix hadolint DL3025

* chore: ignore DL4006 in hadolint config

* fix(images): add pipefail to SHELL and enable DL4006 linting

* Add cleaning to images

* Add DL3003 to the ignored. It's breaking self-contained RUN

single layer idea.

* More fixes on DL3032

* SC2086 -> disable in hadolint we want the var split

* fix(images): resolve DL3027 and other linting issues

* fix(images): resolve DL3009 and fix cd command in nodejs images

* fix(images): consolidate RUN instructions to fix DL3059

* fix(images): use wget --progress=dot:giga to fix DL3047

* fix(images): replace ADD with COPY to fix DL3020

* fix(images): replace wget with curl to fix DL4001

* fix(images): add --no-install-recommends to fix DL3015

* Fix SC2155 and SC2043

* fix(images): comprehensive hadolint and shellcheck fixes

* fix(images): resolve remaining SC2155 in erlang dockerfile

* Add SC1091 to ignored hadolint/shellcheck rules

* Multiple fixes for the Dockerfiles

* remove old files

* Fix last hadolint warning

* Fixes for wget that was changed with sed

* Remove build.log

* Fix double --progress=dot:giga in wget golang images

diff --git a/containers/images/postgres-18/Dockerfile b/containers/images/postgres-18/Dockerfile
--- a/containers/images/postgres-18/Dockerfile
+++ b/containers/images/postgres-18/Dockerfile
@@ -1,4 +1,5 @@
 FROM sourcemation/debian-13-slim:latest
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 ARG BUILD_DATE
 ARG TARGETARCH
@@ -47,9 +48,9 @@ RUN set -eux; \
     apt-get install -y --no-install-recommends ca-certificates wget; \
     rm -rf /var/lib/apt/lists/*; \
     dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
-    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
-    export GNUPGHOME="$(mktemp -d)"; \
+    wget --progress=dot:giga -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+    wget --progress=dot:giga -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
     gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
     gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
     gpgconf --kill all; \
@@ -67,7 +68,10 @@ RUN set -eux; \
 # if this file exists, we're likely in "debian:xxx-slim", and locales are thus being excluded so we need to remove that exclusion (since we need locales)
             grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker; \
             sed -ri '/\/usr\/share\/locale/d' /etc/dpkg/dpkg.cfg.d/docker; \
-            ! grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker; \
+    fi; \
+    if grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker; then \
+        echo "Failed to remove locale exclusion from /etc/dpkg/dpkg.cfg.d/docker"; \
+        exit 1; \
     fi; \
     apt-get update; apt-get install -y --no-install-recommends locales; rm -rf /var/lib/apt/lists/*; \
     echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen; \
@@ -87,7 +91,7 @@ RUN mkdir /docker-entrypoint-initdb.d
 
 RUN set -ex; \
     key='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8'; \
-    export GNUPGHOME="$(mktemp -d)"; \
+    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
     mkdir -p /usr/local/share/keyrings/; \
     gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
     gpg --batch --export --armor "$key" > /usr/local/share/keyrings/postgres.gpg.asc; \
@@ -99,7 +103,6 @@ RUN set -ex; \
 # see note below about "*.pyc" files
     export PYTHONDONTWRITEBYTECODE=1; \
     \
-    dpkgArch="$(dpkg --print-architecture)"; \
     aptRepo="[ signed-by=/usr/local/share/keyrings/postgres.gpg.asc ] http://apt.postgresql.org/pub/repos/apt/ trixie-pgdg main $PG_MAJOR"; \
     echo "deb $aptRepo" > /etc/apt/sources.list.d/pgdg.list; \
     apt-get update; \
@@ -130,10 +133,8 @@ RUN set -eux; \
     sed -ri "s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '*'!" /usr/share/postgresql/postgresql.conf.sample; \
     grep -F "listen_addresses = '*'" /usr/share/postgresql/postgresql.conf.sample
 
-RUN install --verbose --directory --owner postgres --group postgres --mode 3777 /var/run/postgresql
-
-# this 1777 will be replaced by 0700 at runtime (allows semi-arbitrary "--user" values)
-RUN install --verbose --directory --owner postgres --group postgres --mode 1777 "$PGDATA"
+RUN install --verbose --directory --owner postgres --group postgres --mode 3777 /var/run/postgresql \
+    && install --verbose --directory --owner postgres --group postgres --mode 1777 "$PGDATA"
 
 COPY docker-entrypoint.sh docker-ensure-initdb.sh /usr/local/bin/
 RUN ln -sT docker-ensure-initdb.sh /usr/local/bin/docker-enforce-initdb.sh
